version: "1.1"
name: gorchain
description: "Gorchain validator node (Agave/Solana fork)"
repos:
  - github.com/gorbagana-dev/gorchain
containers:
  - gorbagana/gorchain-validator
  - gorbagana/envoy-proxy
pods:
  - gorchain
