{
 "title": "Gorchain Transactions",
 "tags": [
  "gorchain",
  "transactions"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction Rate (Attempted Processing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "transactions_attempted_processing_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Attempted" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Commits (Total vs Successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       { "params": [ "committed_transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Committed" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "committed_transactions_with_successful_result_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Successful" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "retryable_errored_transaction_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Retryable Errors" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "nonretryable_errored_transactions_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Non-retryable Errors" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "executed_transactions_failed_commit_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Failed Commit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "committed_transactions_with_successful_result_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Succeeded" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "transactions_attempted_processing_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Attempted" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "account_lock_throttled_transactions_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Account Lock Throttled" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "cost_model_throttled_transactions_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cost Model Throttled" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "account_locks_limit_throttled_transactions_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Account Locks Limit Throttled" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Execution Time (per worker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "banking_stage_worker_timing",
     "select": [
      [
       { "params": [ "load_execute_us" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Processed (per worker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "banking_stage_worker_counts",
     "select": [
      [
       { "params": [ "processed_transactions_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Processing Time Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "banking_stage_worker_timing",
     "select": [
      [
       { "params": [ "freeze_lock_us" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Freeze Lock" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "banking_stage_worker_timing",
     "select": [
      [
       { "params": [ "record_us" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Record" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "banking_stage_worker_timing",
     "select": [
      [
       { "params": [ "commit_us" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Commit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Transaction Error Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_transaction_errors",
     "select": [
      [
       { "params": [ "account_in_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Account In Use" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_transaction_errors",
     "select": [
      [
       { "params": [ "blockhash_not_found" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Blockhash Not Found" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_transaction_errors",
     "select": [
      [
       { "params": [ "blockhash_too_old" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Blockhash Too Old" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_transaction_errors",
     "select": [
      [
       { "params": [ "already_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Already Processed" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_transaction_errors",
     "select": [
      [
       { "params": [ "instruction_error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Instruction Error" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Buffer Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       { "params": [ "total_new_valid_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Valid Packets" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       { "params": [ "newly_buffered_packets_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffered" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "banking_stage-vote_slot_packet_counts",
     "select": [
      [
       {
        "params": [
         "end_of_slot_unprocessed_buffer_len"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Unprocessed Buffer" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}